---
title: "EDA"
author: "Sri Santhosh Hari"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
library(tidyverse)
library(magrittr)
library(tseries)
library(forecast)

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```


```{r, echo=F}
# Load data and add Mon column in date format
train_data <- read_csv("Data/train.csv")
train_data <- na.omit(train_data)
train_data$Mon <- seq.Date(as.Date("1987/1/1"), as.Date("2010/12/1"), by = "month")
```

We first visualize how the variable of importance, `Bankruptcy Rate`, has changed over the years.

```{r, echo=F, fig.cap="\\label{fig:BRTrend}Monthly Canadian Bankruptcy Rates (1987 - 2010)"}
train_data %>% 
  ggplot(aes(x=Mon))+
  geom_line(aes(y=scale(Bankruptcy_Rate)))+
  labs(x='Time', y='Bankruptcy Rate', title='')
```

It can be observed from Figure \ref{fig:BRTrend} that the bankruptcy rates have generally increased since 1987 with significant increase in later half of 2000's, which can be attributed to the global financial crisis/recession.

```{r, echo=F}
train_data %>% 
  ggplot(aes(x=factor(lubridate::month(train_data$Mon))))+
  geom_boxplot(aes(y=Bankruptcy_Rate,alpha=0.5),show.legend=F)+
  scale_x_discrete(labels=substr(month.name,1,3))+
  labs(x="Month", y="Monthly Bankruptcy Rate", title="Bankruptcy rates across months")
```

```{r, echo=F}
train_data %>% 
  ggplot(aes(x=Mon))+
  geom_line(aes(y=scale(Bankruptcy_Rate), color='Bankruptcy Rate'))+
  geom_line(aes(y=scale(Unemployment_Rate), color='Unemployment Rate'))+
  geom_line(aes(y=scale(Population), color='Population'))+
  geom_line(aes(y=scale(House_Price_Index), color='House Price Index'))+
  labs(x='Time', y='Scaled Variable', color='')
```


```{r, echo=F, warning=F, message=F}
train_data %>% 
  ggplot(aes(x=Mon))+
  geom_line(aes(y=scale(Bankruptcy_Rate), color='Bankruptcy Rate'))+
  geom_line(aes(y=scale(House_Price_Index), color='House Price Index'))+
  geom_line(aes(y=scale(dplyr::lag(train_data$House_Price_Index,18)),
                color='Lagged House Price Index'))+
  labs(x='Time', y='Scaled Variable', color='')
```

```{r, echo=F}
p1 <- train_data %>% ggplot() +
  geom_point(aes(x=Bankruptcy_Rate,y=House_Price_Index,alpha=0.5), show.legend = F)
p2 <- train_data %>% ggplot() +
  geom_point(aes(x=Bankruptcy_Rate,y=dplyr::lag(train_data$House_Price_Index,18),
                 alpha=0.5), show.legend = F)
p3 <- train_data %>% ggplot() +
  geom_point(aes(x=Bankruptcy_Rate,y=Population, alpha=0.5), show.legend = F)
p4 <- train_data %>% ggplot() +
  geom_point(aes(x=Bankruptcy_Rate,y=Unemployment_Rate, alpha=0.5), show.legend = F)
multiplot(p1,p3,p2,p4, cols=2)
```

```{r, echo=F}
# Correlation Check
knitr::kable(round(cor(train_data[2:5])*100,2))
```

```{r, echo=F}
train_mod <- train_data[2:5]
train_mod$HPI_lag <- dplyr::lag(train_mod$House_Price_Index,18)
lagged_cor <- cor(train_mod$Bankruptcy_Rate[c(19:288)], train_mod$HPI_lag[c(19:288)])
round(lagged_cor*100,2)
```
